site_name: 软件设计能力测试
theme:
  name: material
  language: zh
  palette:
    primary: blue
    accent: light blue

nav:
  - 首页: index.md
  - 系统设计:
      - 系统设计: "系统设计/intro.md"
      - 日志系统设计: "系统设计/日志系统设计/intro.md"
      - 缓存系统设计: "系统设计/缓存系统设计/intro.md"
  - 存储:
      - Redis: "存储/redis/intro.md"
      - Kafka: "存储/kafka/intro.md"
      - MySQL: "存储/mysql/intro.md"
  - 编码设计: "编码设计/intro.md"
  - 基础设施: "基础设施/docker-k8s/intro.md"
  - AI:
      - LLM: "ai/llm/intro.md"
      - RAG: "ai/rag/intro.md"
